name: Cypress Regression Suite Execution
on:
  workflow_dispatch:
    inputs:
      specfiles:
        description: Define spec path
        required: true
        default: cypress/e2e/MSIII/**
# on:
#   schedule:
#     - cron: '*/60 * * * *'
# on:
#   push: 
#     branches: [ main ]
jobs:
  cypress-run:
    runs-on: self-hosted
    container: cypress/browsers:chrome67
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    
    - name: Chrome Browser run
      run: | 
        npm run cypress/e2e/MSIII/**
    
    - name: Upload screenshot for failed Test Scripts
      # parallel: true

      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
